Update degradations.py
To avoid the following error:
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

You need to change line 8 in the following file:
.venv/lib/python3.12/site-packages/basicsr/data/degradations.py

Replace this line:
torchvision.transforms.functional_tensor import rgb_to_grayscale
With this line:
torchvision.transforms.functional import rgb_to_grayscale